### ISSUE TITLE
Error on example

### ISSUE THREAD

**Issue by davidcralph** [DevinThePancake/azlyricsman#3]
Error:
```
const get = lyrics.get('Meme Machine').then((song) => {
                   ^

TypeError: lyrics.get is not a function
    at Object.<anonymous> (C:\Users\<yes u>\Desktop\<oh ok>.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
```

**Comment by telkenes** [comment]
its cause it is a class
```js
const lyrics = require('azlyricsman');
const lyr = new lyrics()
const get = lyr.get('Meme Machine').then((song) => {
   console.log(`Lyrics for ${song.song} by ${song.artist}:\n${song.lyrics}`);
}).catch(e => console.error(e));```
this should work

**Comment by davidcralph** [comment]
i see, thanks
